# Generated by Django 3.1.1 on 2020-09-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(choices=[('Eyes', 'Eyes'), ('Mouth', 'Mouth'), ('Wrist', 'Wrist'), ('Hand', 'Hand'), ('Elbow', 'Elbow'), ('Message', 'Message'), ('Other', 'Other')], default='Eyes', max_length=15)),
                ('description', models.TextField(default='', max_length=1000)),
                ('reporter', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
