# Generated by Django 3.1.1 on 2020-09-01 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='problem_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
