# Generated by Django 3.1.1 on 2020-09-01 22:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_problem_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='problem',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Eyes', 'Eyes'), ('Mouth', 'Mouth'), ('Wrist', 'Wrist'), ('Hand', 'Hand'), ('Elbow', 'Elbow'), ('Message', 'Message'), ('Other', 'Other')], max_length=41),
        ),
    ]
